name: The next big thing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.287076941691339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff9632'
    - '#000000'
    - '#a56c5e'
    - '#4681ae'
  brandStrength: 1
  lightness: 0.3625291346106678
  saturation: 0.2270788096357137
  rhythmicContrast: 0.41829378926195204
purpose: []
